//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.29 at 12:24:44 PM BRT 
//


package br.gov.stf.estf.publicacao.model.util;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.gov.stf.estf.publicacao.model.util package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _ObjetoIncidente_QNAME = new QName("", "objetoIncidente");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.gov.stf.estf.publicacao.model.util
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Partes }
     * 
     */
    public Partes createPartes() {
        return new Partes();
    }

    /**
     * Create an instance of {@link Partes.Parte }
     * 
     */
    public Partes.Parte createPartesParte() {
        return new Partes.Parte();
    }

    /**
     * Create an instance of {@link ObjetoIncidente }
     * 
     */
    public ObjetoIncidente createObjetoIncidente() {
        return new ObjetoIncidente();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjetoIncidente }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "objetoIncidente")
    public JAXBElement<ObjetoIncidente> createObjetoIncidente(ObjetoIncidente value) {
        return new JAXBElement<ObjetoIncidente>(_ObjetoIncidente_QNAME, ObjetoIncidente.class, null, value);
    }

}
