package br.gov.stf.estf.processostf.model.util;

public enum ConstanteAndamento {
	// ************************** Repercussão Geral **********************/
	DECISAO_EXISTENCIA_REPERCUSSAO_GERAL_JULGADO_MERITO((long) 6308), 
	AGRAVO_PROVIDO_E_JULGADO_MERITO_TEMA_REPERCUSSAO_GERAL(	(long) 6309), 
	SUBSTITUI_PARADIGMA_DE_REPERCUSSAO_GERAL((long) 8251), 
	DECISAO_EXISTENCIA_REPERCUSSAO_GERAL((long) 6300),
	DECISAO_INEXISTENCIA_REPERCUSSAO_GERAL((long) 6301),
	DECISAO_INEXISTENCIA_CONTITUCIONAL_REPERCUSSAO_GERAL((long) 6306), 
	INICIADA_ANALISE_REPERCUSSAO_GERAL((long) 7602), 
	LANCAMENTO_INDEVIDO1((long) 7700), LANCAMENTO_INDEVIDO2((long) 1067), 
	JULGADO_MERITO_DE_TEMA_COM_REPERCUSSAO_GERAL((long) 6307), 
	JULGADO_MERITO_DE_TEMA_COM_REPERCUSSAO_GERAL_SEM_TESE((long) 8562),
	MERITO_DA_REPERCUSSAO_GERAL_JULGADO_NO_PROCESSO((long) 8243), 
	SUBSTITUIDO_PARA_JULGAMENTO_DE_TEMA_DE_REPERCUSSAO_GERAL_PELO_PROCESSO(	(long) 8242),
	AFETADO_AO_PLENARIO((long)609),
	SUSPENSO_O_JULGAMENTO((long)7205),  
	VISTA_MINISTRO((long)8304);
		
	private Long codigo;
	
	private ConstanteAndamento(Long codigo){
		this.codigo = codigo;
	}
	
	public Long getCodigo(){
		return this.codigo;
	}
	
}
