/* Auto generated by Twist. Please do not delete this file */

import org.openqa.selenium.WebDriver;

import org.springframework.beans.factory.annotation.Autowired;

import com.thoughtworks.twist.core.execution.TwistScenarioDataStore;

import com.thoughtworks.twist.core.BeforeEachStep;

import com.thoughtworks.twist.core.AfterEachStep;

public class ScenarioExecutionHooks {

	private WebDriver browser;

	@Autowired
	private TwistScenarioDataStore scenarioStore;

	public ScenarioExecutionHooks(WebDriver browser) {
		this.browser = browser;
	}

	@BeforeEachStep
	public void beforeEachStep() throws Exception {
	
	}

	@AfterEachStep
	public void afterEachStep() throws Exception {
	
	}

}