package br.jus.stf.estf.decisao.support.action.support;

import br.jus.stf.estf.decisao.support.action.handlers.RestrictHandler;

/**
 * Fornece a lista de identificadores para as ações. Relaciona a ação à transação
 * cadastrada na base. Utilizada pelo handler de segurança {@link RestrictHandler}
 * para carregar os perfis da transação e comparar com os perfis do usuário.
 * 
 * @author Rodrigo Barreiros
 * @since 26.05.2010
 */
public enum ActionIdentification {
	
	ADICIONAR_PROCESSO_A_UMA_LISTA(1),
    ADICIONAR_TEXTO_A_UMA_LISTA(2),
    LIBERAR_PARA_JULGAMENTO(3),
    ASSINAR_DIGITALMENTE(4),
    CANCELAR_ASSINATURA(5),
    CONCLUIR_REVISAO(6),
    CONSULTAR_ATA_DE_JULGAMENTO(7),
    CONSULTAR_INFORMACOES_DE_UM_TEXTO(8),
    CONSULTAR_INFORMACOES_DE_UM_PROCESSO(9),
    CONSULTAR_TEXTOS_NAO_PUBLICOS_DE_OUTROS_MINISTROS(10),
    RESTRINGIR_ACESSO_AO_TEXTO(11),
    CUSTOMIZAR_FUNCIONAMENTO_DO_SISTEMA(12),
    CRIAR_TEXTO_SEMELHANTE(13),
    CRIAR_EDITAR_LISTA_DE_TEXTOS_IGUAIS(14),
    EDITAR_ESPELHO(15),
    EDITAR_LISTA_DE_PROCESSOS(16),
    EDITAR_LISTA_DE_TEXTOS(17),
    EDITAR_TEXTO(18),
    EXCLUIR_LISTA_DE_PROCESSOS(19),
    EXCLUIR_LISTA_DE_TEXTOS(20),
    EXCLUIR_PROCESSO_DE_UMA_LISTA(22),
    EXCLUIR_TEXTO(23),
    EXCLUIR_TEXTO_DE_UMA_LISTA(25),
    IMPRIMIR_LISTA_DE_PROCESSOS(26),
    IMPRIMIR_LISTA_DE_TEXTOS(27),
    IMPRIMIR_MINUTA(28),
    IMPRIMIR_TEXTO(29),
    IMPRIMIR_TEXTOS_DOS_PROCESSOS(30),
    JUNTAR_PECAS(31),
    LIBERAR_EMENTA_E_ACORDAO_PARA_PUBLICACAO(32),
    LIBERAR_PARA_ASSINATURA(33),
    LIBERAR_PARA_PUBLICACAO(34),
    LIBERAR_PARA_REVISAO(35),
    NOVA_LISTA_DE_PROCESSOS(36),
    NOVA_LISTA_DE_TEXTOS(37),
    NOVO_TEXTO(38),
    PESQUISA_AVANCADA_DE_PROCESSOS(39),
    PESQUISA_AVANCADA_DE_TEXTOS(40),
    PESQUISA_DE_LISTAS(41),
    SUSPENDER_LIBERACAO(42),
    SUSPENDER_PUBLICACAO(43),
    TORNAR_TEXTO_SEMELHANTE(44),
    VOLTAR_PARA_ELABORACAO_DE_EM_REVISAO(45),
    VOLTAR_PARA_REVISAO(46),
    CRIAR_CONTROLE_DE_VOTOS(47),
    DESFAZER_JUNTADA(48),
    IMPRIMIR_COPIA(49),
	EDITAR_TEXTO_EM_ELABORACAO(50),
	EDITAR_TEXTO_EM_REVISAO(51),
	EDITAR_TEXTO_REVISADO(52),
	EDITAR_TEXTO_LIBERADO_PARA_ASSINATURA(53),
	ACESSAR_TODOS_OS_GABINETES(54),
	CRIAR_INCIDENTE_DE_JULGAMENTO(55),
	VOLTAR_PARA_ELABORACAO_DE_REVISADO(56),
	VOLTAR_PARA_ELABORACAO_DE_LIBERADO_PARA_ASSINATURA(57),
	IMPRIMIR_SEM_MARCA_D_AGUA(58),
	ATUALIZAR_MACROS_ATALHOS(59),
	PESQUISAR_COMUNICACOES(60),
	ASSINAR_DIGITALMENTE_COMUNICACOES(61),
	DEVOLVER_COMUNICACOES(62),
	TESTAR_ASSINATURA_DIGITAL(63),
	ASSINAR_CONTINGENCIALMENTE(64),
	TESTAR_ASSINATURA_DIGITAL_DE_COMUNICACOES(65),
	REPUBLICAR(66),
	CONFIGURAR_SISTEMA(67),
	EXPORTAR_LISTA_PROCESSOS(68),
	IMPRIMIR_ESPECIAL(71),
	CONFIGURAR_OPCOES_GABINETE(72),
	ACESSO_TEXTOS_RESTRITOS_GABINETE(73),
	DEFINIR_TEXTO_COMO_FAVORITO(74),
	EDITAR_OBSERVACAO_PROCESSO(75),
	GERENCIAR_CATEGORIAS(76),
	CATEGORIZAR_PROCESSOS(77),
	CRIAR_TEXTOS_SEMELHANTES(78),
	EXPORTAR_PROCESSOS(79), 
	DISPONIBILIZAR_VOTO(80),
	VISUALIZAR_VOTO_DISPONIBILIZADO(81),
	EXCLUIR_INCIDENTE(82),
	MOVER_TEXTOS(83),
	LIBERAR_ACORDAO_PARA_PUBLICACAO_PROCESSO_SIGILOSO(84),
	CANCELAR_PEDIDO_DE_DESTAQUE(85);
	
	private final int codigo;
	
	/**
	 * Instancia a classe, informando qual o código da transação relacionado à
	 * ação correspondente.
	 * 
	 * @param codigo o código da transação
	 */
	private ActionIdentification(int codigo) {
		this.codigo = codigo;
	}
	
	/**
	 * Retorna o código da transação relacionada à ação
	 * 
	 * @return o código da transação
	 */
	public int getCodigo() {
		return codigo;
	}
}
