package br.gov.stf.estf.entidade.usuario;

// Generated 01/04/2014 14:47:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import br.gov.stf.estf.entidade.ESTFBaseEntity;

/**
 * @category NOVA_MODELAGEM
 * PessoaEndereco generated by hbm2java
 */
@Entity
@Table(name = "PESSOA_ENDERECO", schema = "CORPORATIVO")
public class PessoaEndereco extends ESTFBaseEntity<Long> {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6418951800860357615L;
	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="PESSOA_ENDERECO_SEQUENCE")
	@SequenceGenerator(name = "PESSOA_ENDERECO_SEQUENCE", sequenceName = "CORPORATIVO.SEQ_PESSOA_ENDERECO", allocationSize = 1)	
	@Column(name = "SEQ_PESSOA_ENDERECO", unique = true, nullable = false, precision = 10, scale = 0)
	private Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SEQ_PESSOA", nullable = false)
	private Pessoa pessoa;
	
	@Column(name = "DSC_LOGRADOURO", length = 250)
	private String logradouro;
	
	@Column(name = "NUM_LOGRADOURO", length = 20)
	private String numeroLogradouro;
	
	@Column(name = "DSC_BAIRRO")
	private String bairro;
	
	@Column(name = "COD_CEP", length = 10)
	private String cep;
	
	@Column(name = "NOM_CIDADE", length = 70)
	private String cidade;
	
	@Column(name = "SIG_UF", length = 2)
	private String uf;
	
	@Column(name = "DSC_COMPLEMENTO")
	private String complemento;
	
	@Column(name = "NOM_PAIS", length = 50)
	private String pais;
	
	@Column(name = "TIP_ENDERECO", length = 1)
	private String tipoEndereco;


	public PessoaEndereco() {
	}

	public PessoaEndereco(long id, Pessoa pessoa) {
		this.id = id;
		this.pessoa = pessoa;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Pessoa getPessoa() {
		return pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	public String getLogradouro() {
		return logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	public String getNumeroLogradouro() {
		return numeroLogradouro;
	}

	public void setNumeroLogradouro(String numeroLogradouro) {
		this.numeroLogradouro = numeroLogradouro;
	}

	public String getBairro() {
		return bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	public String getCep() {
		return cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	public String getCidade() {
		return cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	public String getUf() {
		return uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	public String getComplemento() {
		return complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	public String getPais() {
		return pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}


	public String getTipoEndereco() {
		return tipoEndereco;
	}

	public void setTipoEndereco(String tipoEndereco) {
		this.tipoEndereco = tipoEndereco;
	}	

}
